baseURL = "https://ingressive.cloud/"
title = "Ingressive.cloud"
enableGitInfo = true

[languages]
  [languages.en]
    locale = "en-us"

[params]
  description = "Edge Infrastructure for Kubernetes"
  consoleURL = "https://console.ingressive.cloud/login"
  discordURL = "/discord"

[menu]
  [[menu.main]]
    name = "Docs"
    url  = "/docs/"
    weight = 10
  [[menu.main]]
    name = "Blog"
    url  = "/posts/"
    weight = 15
  [[menu.main]]
    name = "Log In"
    url  = "https://console.ingressive.cloud/login"
    weight = 20

disableKinds = ["taxonomy"]

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "JSON"]

[markup]
  [markup.highlight]
    style = "dracula"
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
