apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingressive-www
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/ingressive-cloud/www.ingressive.cloud
    targetRevision: main
    path: kubernetes
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ingressive-www

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
